(deftheme city-night 
  "Based on a photo of Morgantown city skyline at night")

(custom-theme-set-faces
 `city-night
 `(default ((t (:background "#111417" :foreground "#D1C1A7" ))))
 `(bold ((t (:bold t))))
 `(bold-italic ((t (:bold t))))
 `(border-glyph ((t (nil))))
 `(buffers-tab ((t (:background "#111417" :foreground "#D1C1A7"))))
 `(gui-element ((t (:background "#A68F86" :foreground "#101011"))))
 `(font-lock-comment-face ((t (:italic t :foreground "#413E3A"))))
 `(mode-line ((t (:background "#4A5B5F" :foreground "#101011"))))
 `(highlight ((t (:background "#1A1714"))))
 `(font-lock-regexp-grouping-construct ((t (:foreground "#6D483D"))))
 `(font-lock-warning-face ((t (:bold t :foreground "#684D37"))))
 `(font-lock-function-name-face ((t (:foreground "#BE965A"))))
 `(font-lock-variable-name-face ((t (:foreground "#BE965A"))))
 `(font-lock-doc-string-face ((t (:foreground "#533917"))))
 `(font-lock-regexp-grouping-backslash ((t (:foreground "#373822"))))
 `(font-lock-keyword-face ((t (:foreground "#684D37"))))
 `(text-cursor ((t (:background "#3E3923" :foreground "#101011"))))
 `(font-lock-constant-face ((t (:foreground "#4A5B5F"))))
 `(font-lock-string-face ((t (:foreground "#587435"))))
 `(highline-face ((t (:background "#474C45"))))
 `(font-lock-builtin-face ((t (:foreground "#303C49"))))
 `(font-lock-type-face ((t (:foreground "#3A556A"))))
 `(font-lock-preprocessor-face ((t (:foreground "#2C465D"))))
 `(region ((t (:background "#313E4D"))))
 `(font-lock-reference-face ((t (:foreground "#202C38"))))
 `(italic ((t (nil))))
 `(left-margin ((t (nil))))
 `(toolbar ((t (nil))))
 `(underline ((nil (:underline nil))))
 `(zmacs-region ((t (:background "#D1C1A7" :foreground "#314154")))))

(provide-theme 'city-night)
